### ISSUE TITLE
juniper devices

### ISSUE THREAD

**Issue by shigechika** [hogehuga/snmp2cpe#2]
cpeName  :Can not match CPE.
sysDescr :Juniper Networks, Inc. mx240 internet router, kernel JUNOS 18.4R3-S7.2, Build date: 2021-02-03 13:31:24 UTC Copyright (c) 1996-2021 Juniper Networks, Inc.

cpeName  :Can not match CPE.
sysDescr :Juniper Networks, Inc. mx5-t internet router, kernel JUNOS 18.4R3-S7.2, Build date: 2021-02-03 14:51:07 UTC Copyright (c) 1996-2021 Juniper Networks, Inc.

cpeName  :Can not match CPE.
sysDescr :Juniper Networks, Inc. srx4600 internet router, kernel JUNOS 18.4R3-S7.2, Build date: 2021-02-03 13:31:24 UTC Copyright (c) 1996-2021 Juniper Networks, Inc.

cpeName  :Can not match CPE.
sysDescr :Juniper Networks, Inc. srx345 internet router, kernel JUNOS 18.4R3-S7.2, Build date: 2021-02-03 14:36:45 UTC Copyright (c) 1996-2021 Juniper Networks, Inc.

cpeName  :Can not match CPE.
sysDescr :Juniper Networks, Inc. srx300 internet router, kernel JUNOS 18.4R3-S7.2, Build date: 2021-02-03 14:36:45 UTC Copyright (c) 1996-2021 Juniper Networks, Inc.

cpeName  :Can not match CPE.
sysDescr :Juniper Networks, Inc. qfx5110-48s-4c Ethernet Switch, kernel JUNOS 18.4R3-S7.2, Build date: 2021-02-03 13:31:24 UTC Copyright (c) 1996-2021 Juniper Networks, Inc.

cpeName  :Can not match CPE.
sysDescr :Juniper Networks, Inc. ex4300-32f Ethernet Switch, kernel JUNOS 18.4R3-S7.2, Build date: 2021-02-03 14:51:07 UTC Copyright (c) 1996-2021 Juniper Networks, Inc.

cpeName  :Can not match CPE.
sysDescr :Juniper Networks, Inc. ex3400-24t Ethernet Switch, kernel JUNOS 18.4R3-S7.2, Build date: 2021-02-03 13:35:20 UTC Copyright (c) 1996-2021 Juniper Networks, Inc.

cpeName  :Can not match CPE.
sysDescr :Juniper Networks, Inc. ex2300-24t Ethernet Switch, kernel JUNOS 18.4R3-S7.2, Build date: 2021-02-03 13:35:20 UTC Copyright (c) 1996-2021 Juniper Networks, Inc.

cpeName  :Can not match CPE.
sysDescr :Juniper Networks, Inc. ex4300-32f Ethernet Switch, kernel JUNOS 20.4R2-S2.2, Build date: 2021-08-12 00:07:44 UTC Copyright (c) 1996-2021 Juniper Networks, Inc.

**Comment by hogehuga** [comment]
I forget closed..
